public with sharing class Constant {
   
    public static final String STAGE_NAME       = 'New'; // System.Label. ;
    public static final String DEAL_ORG_TYPE    = 'Department';
    
    public static final string NEW_BUSSINESS_CLOSEDSTAGE      	= 'Closed Won';
    public static final string EXISTING_BUSSINESS_CLOSEDSTAGE 	= 'Closed/Won';
    public static final string CUSTOMER_SUCCESS_STAGE 			= 'New Customer Waiting';
}